[workspace]
members = [ "crates/*" ]

[workspace.package]
authors = [
    "ElKowar <5300871+elkowar@users.noreply.github.com>",
    "Charlotte Meyer <dev@buffet.sh>",
    "Pedro Burgos <druskus20@gmail.com>",
    "cpli <dev@cpli.in>",
]
categories = ["text-processing"]
keywords = ["editor"]
homepage = "https://github.com/bazed-editor/bazed"
repository = "https://github.com/bazed-editor/bazed"
license = "Apache-2.0 OR MIT"

[profile.release]
codegen-units = 1
lto = true
