[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
notice = "deny"
unmaintained = "deny"
vulnerability = "deny"
yanked = "deny"
ignore = [
    "RUSTSEC-2022-0048", # xml-rs
    "RUSTSEC-2023-0018" # tauri -> remove_dir_all
]

[licenses]
copyleft = "deny"
default = "deny"
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-DFS-2016",
    "BSD-3-Clause",
    "CC0-1.0",
    "MIT-0",
    "MPL-2.0",
]

[bans]
highlight = "all"
multiple-versions = "deny"
wildcards = "deny"
skip = [
    { name = "cfg-expr", version = "0.9.1" }, # https://github.com/tauri-apps/webkit2gtk-rs/pull/134
    { name = "getrandom", version = "0.1.16" }, # fixed with next kuchiki release
    { name = "heck", version = "0.3.3" }, # https://github.com/tauri-apps/webkit2gtk-rs/pull/134
    { name = "itoa", version = "0.4.8" }, # blocked by kuchiki (cssparser 0.29)
    { name = "phf", version = "0.8.0" }, # fixed with next kuchiki release
    { name = "phf_generator", version = "0.8.0" }, # fixed with next kuchiki release
    { name = "phf_macros", version = "0.8.0" }, # fixed with next kuchiki release
    { name = "phf_shared", version = "0.8.0" }, # fixed with next kuchiki release
    { name = "rand", version = "0.7.3" }, # fixed with next kuchiki release
    { name = "rand_chacha", version = "0.2.2" }, # fixed with next kuchiki release
    { name = "rand_core", version = "0.5.1" }, # fixed with next kuchiki release
    { name = "rustc_version", version = "0.3.3" },
    { name = "semver", version = "0.11.0" },
    { name = "system-deps", version = "5.0.0" }, # blocked by webkit2gtk-rs (javascriptcore-rs 0.17.0)
    { name = "uuid", version = "0.8.2" },
    { name = "version-compare", version = "0.0.11" },
    { name = "wasi", version = "0.9.0+wasi-snapshot-preview1" },
    { name = "windows_aarch64_msvc", version = "0.39.0" },
    { name = "windows_i686_gnu", version = "0.39.0" },
    { name = "windows_i686_msvc", version = "0.39.0" },
    { name = "windows_x86_64_gnu", version = "0.39.0" },
    { name = "windows_x86_64_msvc", version = "0.39.0" },
    { name = "windows-sys", version = "0.42.0" }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
