[package]
name = "bazed"
version = "0.0.0"
edition = "2021"
description = "The bazed editor"
authors.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
