[package]
name = "bazed-core"
version = "0.0.0"
edition = "2021"
authors.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ropey = "1.5.0"
color-eyre.workspace = true
uuid.workspace = true
thiserror.workspace = true
bazed-rpc.workspace = true
tokio.workspace = true
futures.workspace = true
