name: CI
on: [pull_request, push]

env:
  CI: 1
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: -D warnings

jobs:
  rust-tests:
    name: Rust tests
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libgtk-3-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev
    - uses: actions/checkout@v3
    - name: Setup rust toolchain
      run: rustup show
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo test --workspace --all-features --no-run
    - name: Run tests
      run: cargo test --workspace --all-features

  cargo-deny:
    name: Cargo deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check ${{ matrix.checks }}

  rehuko-lint:
    name: Svelte formatting test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install npm packages
      run: npm ci --workspaces
    - name: Lint
      run: npm run lint --workspaces
